spring:
  data:
    mongodb:
      port: 27017
      database: library
mongock:
  change-logs-scan-package:
    - ru.otus.library.mongock.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
