application:
  job:
    chunk-size: 10
    page-size: 10
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-circular-references: true
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true
  data:
    mongodb:
      port: 27017
      database: library
#  mongodb:
#    embedded:
#      version: 3.4.0

