spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: false

    show-sql: false

logging:
  level:
    org:
      springframework:
        security: DEBUG